name: Cache Action
description: Cache npm dependencies
inputs:
  caching:
    description: Indicator for caching
    required: true
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
