name: Cache Dependencies
description: Cache npm dependencies
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        key: node-modules-${{ hashFiles( '**/package-lock.json' ) }}
        path: node-modules
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
